apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fin.fullname" . }}-api-keys
  labels:
    app: {{ template "fin.name" . }}
    chart: {{ template "fin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ALPHAVANTAGE_API_KEY: {{ .Values.secrets.ALPHAVANTAGE_API_KEY | b64enc }}
  COIN_MARKETCAP_API_KEY: {{ .Values.secrets.COIN_MARKETCAP_API_KEY | b64enc }}
  FINNHUB_API_KEY: {{ .Values.secrets.FINNHUB_API_KEY | b64enc }}