apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "homepage.fullname" . }}-bookmarks
  labels:
    app: {{ template "homepage.name" . }}
    chart: {{ template "homepage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  bookmarks.yaml: {{ quote .Values.configmap.config.bookmarks }}