apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "homepage.fullname" . }}-custom-js
  labels:
    app: {{ template "homepage.name" . }}
    chart: {{ template "homepage.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  custom.js: {{ quote .Values.configmap.config.custom_js }}