{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homepage.serviceAccountName" . }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homepage.serviceAccountName" . }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "homepage.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "homepage.serviceAccountName" . }}-view-cluster-crd-status

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homepage.serviceAccountName" . }}-view-cluster-crd-status
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]



{{- end }}
